version: '3'
services: 
  api-heroes:
    # build: .
    image: erickwendel/api-heroes
    ports: 
      - 3000:3000
    environment: 
      MONGO_URL: mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:3.5
    ports: 
      - 27017:2017